### ISSUE TITLE
Windows Compatibility Issue

### ISSUE THREAD

**Issue by sbutner** [JonathanReeve/corpus-list#6]
sh is only supported on linux and osx, with no plans of extending to Windows per the docs. This causes an ImportError on any call to corpus.py in a Windows environment.

**Comment by JonathanReeve** [comment]
Thanks for the feedback! I'm guessing this issue is meant for `corpus-downloader`, and not `corpus-list`? 

I don't really have the means (or money) to test anything on MacOS or Windows, unfortunately. But Linux is free, and easy to get! Plus, virtually all text analysis software works better with a Linux system than with other systems. For Windows, there's the Ubuntu for Windows environment, which is now in the Microsoft store. Corpus-downloader should work nicely there, once you install Python to it. You can also use VirtualBox, or [DH Box](https://dhbox.org) in the cloud. 

I'll add a note to the readme that Windows and MacOS are not supported. Thanks again for the tip!
